# golangci-lint configuration for Discord Command Executor
# Version 2.x configuration format
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  # Use only specific linters (none by default)
  default: none
  
  # Enable specific linters
  enable:
    # Error detection
    - errcheck          # Checks for unchecked errors
    - gosec             # Security issues
    - govet             # Standard Go vet checks
    
    # Code quality
    - gocyclo           # Cyclomatic complexity
    - revive            # Replacement for golint
    - ineffassign       # Ineffectual assignments
    - misspell          # Spelling mistakes
    - unconvert         # Unnecessary type conversions
    - unused            # Unused constants, variables, functions and types
    
    # Performance
    - prealloc          # Slice preallocation
    
    # Style and best practices
    - goconst           # Repeated strings that could be constants
    - gocritic          # Comprehensive Go source code analysis
    - mnd               # Magic number detection
    - nakedret          # Naked returns in long functions
    - unparam           # Unused function parameters
    - whitespace        # Whitespace issues
    
    # Complexity
    - dupl              # Code duplication
    - lll               # Line length limit
  
  # Linter-specific settings
  settings:
    dupl:
      threshold: 100
    
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
    
    gocyclo:
      min-complexity: 15
    
    goconst:
      min-len: 3
      min-occurrences: 3
      ignore-tests: false
      match-constant: true
      numbers: false
      ignore-calls: true
    
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    
    revive:
      rules:
        - name: exported
          arguments: ["checkPrivateReceivers","sayRepetitiveInsteadOfStutters"]
    
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    
    lll:
      line-length: 120
      tab-width: 4
    
    govet:
      enable:
        - fieldalignment
    
    misspell:
      locale: US
      ignore-words:
        - someword
    
    nakedret:
      max-func-lines: 30
    
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    
    unparam:
      check-exported: false
    
    whitespace:
      multi-if: false
      multi-func: false

  # Issues exclusions
  exclusions:
    exclude-dirs:
      - vendor
      - build
      - scripts
    
    exclude-files:
      - ".*\\.pb\\.go$"
      - ".*_generated\\.go$"
    
    exclude:
      - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
      - "Error return value of `.*Close` is not checked"
      - "Error return value of `os.Setenv` is not checked"
      - "Error return value of `os.Unsetenv` is not checked"
      - "Error return value of `.*ReadInConfig` is not checked"
    
    exclude-rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - mnd
          - goconst
          - dupl
          - lll
      
      # Exclude gocritic unnecessaryDefer
      - linters:
          - gocritic
        text: "unnecessaryDefer:"
      
      # Exclude common magic numbers
      - linters:
          - mnd
        text: "Magic number: (0|0\\.5|1|2|8|10|16|32|64|100|128|200|400|404|500|1000|1024|4096|8080)"
      
      # Exclude ineffassign for error shadowing in tests
      - path: _test\.go
        text: "ineffectual assignment to err"
        linters:
          - ineffassign
      
      # Exclude fieldalignment for Config struct (acceptable trade-off for readability)
      - linters:
          - govet
        text: "fieldalignment: struct.*Config.*could be"
    
    exclude-use-default: false
    max-issues-per-linter: 50
    max-same-issues: 3
    new: false
    fix: false

formatters:
  settings:
    goimports:
      local-prefixes: github.com/anchitjain1234/discord-command-executor

severity:
  default-severity: error
  case-sensitive: false